#@tool
extends Node3D
class_name IslandGenerator

const ISLAND_TERRAIN_SHADERS = preload("res://procedural island/config/island_terrain.tres")


@export_group("Map Controls")
@export var generate: bool = false:
	set(value):
		if value:
			island_seed = randi()
			_generate_island()
			generate = false

@export_group("Island Settings")
@export var island_size: float = 100.0
@export var max_height: float = 50.0
@export var sand_level: float = 2.0
@export var island_seed: int = 0
@export var noise: FastNoiseLite
@export var subdivision : Vector2 = Vector2(100, 100)

@export_group("Foliage")
@export var foliage_types: Array[FoliageSetting]

var terrain_mesh_node

enum TerrainNoiseType {
	CELLULAR = FastNoiseLite.TYPE_CELLULAR,
	PERLIN = FastNoiseLite.TYPE_PERLIN,
	SIMPLEX = FastNoiseLite.TYPE_SIMPLEX,
	SIMPLEX_SMOOTH = FastNoiseLite.TYPE_SIMPLEX_SMOOTH
}

@export var current_terrain_type : TerrainNoiseType = TerrainNoiseType.CELLULAR:
	set(value):
		current_terrain_type = value
		if noise:
			noise.noise_type = current_terrain_type as int

#var island_data : Dictionary = {}

func _ready() -> void:
	
	if not noise:
		noise = FastNoiseLite.new()

	noise.noise_type = current_terrain_type as int
	
	await get_tree().process_frame
	_generate_island()
	
	IslandManager.island_data[self.get_instance_id()] = {"position":global_position,"size":island_size}

func _generate_island() -> void:
	if not noise: 
		noise = FastNoiseLite.new()
	noise.noise_type = current_terrain_type as int
	# 1. Setup Mesh Data
	noise.seed = island_seed
	var plane = PlaneMesh.new()
	plane.size = Vector2(island_size, island_size)
	plane.subdivide_width = int(subdivision.x)
	plane.subdivide_depth = int(subdivision.y)
	
	# Extract ALL data generated by the PlaneMesh (Vertices, UVs, etc.)
	var st = SurfaceTool.new()
	st.create_from(plane, 0)
	var mesh_data = st.commit_to_arrays()
	
	# Grab a reference to the vertex array so we can modify it
	var vertices = mesh_data[Mesh.ARRAY_VERTEX]
	
	# 2. Shape the terrain
	for i in range(vertices.size()):
		var pos = vertices[i]
		var dist = Vector2(pos.x, pos.z).length()
		var max_radius = island_size / 2.0
		
		# --- ORGANIC SHAPE WARPING ---
		var warp_scale = max_radius * 0.4 
		var warp_x = noise.get_noise_2d(pos.x + 1000.0, pos.z) * warp_scale
		var warp_z = noise.get_noise_2d(pos.x, pos.z + 1000.0) * warp_scale
		
		var distorted_dist = Vector2(pos.x + warp_x, pos.z + warp_z).length()
		var beach_radius = max_radius * 0.5
		
		# --- CONE EFFECT ---
		var dist_norm = clamp(dist / max_radius, 0.0, 1.0)
		var expansion_factor = lerp(1.0, 2.0, smoothstep(0.0, 1.0, dist_norm))
		pos.x *= expansion_factor
		pos.z *= expansion_factor
		
		# --- HEIGHT & FALLOFF ---
		var raw_noise = (noise.get_noise_2d(pos.x, pos.z) + 1.0) * 0.5
		
		if distorted_dist <= beach_radius:
			var island_norm = distorted_dist / beach_radius
			pos.y = (raw_noise * max_height) * (1.0 - island_norm)
		else:
			var underwater_dist = distorted_dist - beach_radius
			var dropoff_zone = max_radius - beach_radius
			var drop_progress = clamp(underwater_dist / dropoff_zone, 0.0, 1.0)
			var curve = pow(drop_progress, 1.5)
			pos.y = lerp(0.0, -1000.0, curve)
			
		vertices[i] = pos
		
	# Put the modified vertices back into the main mesh data array
	mesh_data[Mesh.ARRAY_VERTEX] = vertices
	
	# 3. Create the updated mesh while preserving UVs
	var array_mesh = ArrayMesh.new()
	array_mesh.add_surface_from_arrays(Mesh.PRIMITIVE_TRIANGLES, mesh_data)
	
	# Recalculate lighting normals based on the new wobbly shape
	var final_st = SurfaceTool.new()
	final_st.create_from(array_mesh, 0)
	final_st.generate_normals()
	var new_mesh = final_st.commit()

	# 4. Apply to MeshInstance3D
	if not terrain_mesh_node:
		terrain_mesh_node = MeshInstance3D.new()
		terrain_mesh_node.name = "TerrainMesh"
		add_child(terrain_mesh_node)
		if Engine.is_editor_hint() and get_tree() and get_tree().edited_scene_root:
			terrain_mesh_node.owner = get_tree().edited_scene_root
	
	terrain_mesh_node.mesh = new_mesh
	
	# material_override is safer than set_surface_override_material for procedural meshes
	terrain_mesh_node.material_override = ISLAND_TERRAIN_SHADERS
	
	# 5. Create/Update Collision
	var static_body = terrain_mesh_node.get_node_or_null("StaticBody3D")
	if not static_body:
		static_body = StaticBody3D.new()
		static_body.name = "StaticBody3D"
		terrain_mesh_node.add_child(static_body)
		static_body.set_collision_layer_value(2, true)
		static_body.set_collision_layer_value(4, true)
		static_body.set_collision_mask_value(2, true)
		static_body.set_collision_mask_value(4, true)
		if Engine.is_editor_hint() and get_tree() and get_tree().edited_scene_root:
			static_body.owner = get_tree().edited_scene_root
	
	var collision_shape = static_body.get_node_or_null("CollisionShape3D")
	if not collision_shape:
		collision_shape = CollisionShape3D.new()
		collision_shape.name = "CollisionShape3D"
		static_body.add_child(collision_shape)
		if Engine.is_editor_hint() and get_tree() and get_tree().edited_scene_root:
			collision_shape.owner = get_tree().edited_scene_root
	
	collision_shape.shape = terrain_mesh_node.mesh.create_trimesh_shape()
	
	# 6. Scatter Foliage
	_scatter_foliage(vertices)

#func _generate_island() -> void:
	#if not noise: return
	#
	## 1. Setup Mesh Data
	#noise.seed = island_seed
	#var plane = PlaneMesh.new()
	#plane.size = Vector2(island_size, island_size)
	#plane.subdivide_width = int(subdivision.x)
	#plane.subdivide_depth = int(subdivision.y)
	#
	#var st = SurfaceTool.new()
	#st.create_from(plane, 0)
	#var mesh_data = st.commit_to_arrays()
	#var vertices = mesh_data[Mesh.ARRAY_VERTEX]
	#var indices = mesh_data[Mesh.ARRAY_INDEX]
	#
	## 2. Shape the terrain
	#for i in range(vertices.size()):
		#var pos = vertices[i]
		#var dist = Vector2(pos.x, pos.z).length()
		#var max_radius = island_size / 2.0
		#
		## --- ORGANIC SHAPE WARPING (Domain Warping) ---
		## We sample the noise at an offset to shift our math, breaking the perfect circle.
		#var warp_scale = max_radius * 0.4 # Controls how dramatic the peninsulas/bays are (40% wobble)
		#
		## Add +1000 to the coordinates so we sample a different part of the noise map 
		## than we use for the actual terrain height.
		#var warp_x = noise.get_noise_2d(pos.x + 1000.0, pos.z) * warp_scale
		#var warp_z = noise.get_noise_2d(pos.x, pos.z + 1000.0) * warp_scale
		#
		## This wobbly distance creates our irregular coastline mask
		#var distorted_dist = Vector2(pos.x + warp_x, pos.z + warp_z).length()
		#
		#var beach_radius = max_radius * 0.5
		#
		## --- CONE EFFECT (Topology) ---
		## We keep the raw 'dist' here so the physical mesh stretches evenly.
		## If we warped this, the 3D triangles might fold over each other!
		#var dist_norm = clamp(dist / max_radius, 0.0, 1.0)
		#var expansion_factor = lerp(1.0, 2.0, smoothstep(0.0, 1.0, dist_norm))
		#pos.x *= expansion_factor
		#pos.z *= expansion_factor
		#
		## --- HEIGHT & FALLOFF ---
		#var raw_noise = (noise.get_noise_2d(pos.x, pos.z) + 1.0) * 0.5
		#
		#if distorted_dist <= beach_radius:
			## ABOVE WATER: Taper using the distorted, organic distance
			#var island_norm = distorted_dist / beach_radius
			#pos.y = (raw_noise * max_height) * (1.0 - island_norm)
		#else:
			## UNDERWATER: Swoop down using the wobbly coordinates
			#var underwater_dist = distorted_dist - beach_radius
			#var dropoff_zone = max_radius - beach_radius
			#
			#var drop_progress = clamp(underwater_dist / dropoff_zone, 0.0, 1.0)
			#var curve = pow(drop_progress, 1.5)
			#
			#pos.y = lerp(0.0, -1000.0, curve)
			#
		#vertices[i] = pos
		#
## Update mesh creation to apply the material
	#if not terrain_mesh_node:
		#terrain_mesh_node = MeshInstance3D.new()
		#terrain_mesh_node.name = "TerrainMesh"
		#add_child(terrain_mesh_node)
		#terrain_mesh_node.owner = get_tree().edited_scene_root
	#
	#var final_st = SurfaceTool.new()
	#final_st.begin(Mesh.PRIMITIVE_TRIANGLES)
	#
	#for v in vertices: final_st.add_vertex(v)
	#for idx in indices: final_st.add_index(idx)
	#
	#final_st.generate_normals()
	#
	## Commit the mesh
	#var new_mesh = final_st.commit()
	#terrain_mesh_node.mesh = new_mesh
	#
	## 3. Apply the material/terrain reference
	#terrain_mesh_node.set_surface_override_material(0, ISLAND_TERRAIN_SHADERS)
	#
	## 4. Create/Update Collision
	#var static_body = terrain_mesh_node.get_node_or_null("StaticBody3D")
	#if not static_body:
		#static_body = StaticBody3D.new()
		#static_body.name = "StaticBody3D"
		#terrain_mesh_node.add_child(static_body)
		#static_body.owner = get_tree().edited_scene_root
		#static_body.set_collision_layer_value(2,true)
		#static_body.set_collision_mask_value(2,true)
	#
	#var collision_shape = static_body.get_node_or_null("CollisionShape3D")
	#if not collision_shape:
		#collision_shape = CollisionShape3D.new() as CollisionShape3D
		#collision_shape.name = "CollisionShape3D"
		#static_body.add_child(collision_shape)
		#collision_shape.owner = get_tree().edited_scene_root
	#
	#collision_shape.shape = terrain_mesh_node.mesh.create_trimesh_shape()
	#
	#
	## 5. Scatter Foliage
	#_scatter_foliage(vertices)

func _scatter_foliage(vertices: PackedVector3Array) -> void:
	var rng = RandomNumberGenerator.new()
	rng.seed = island_seed
	
	# 1. CLEANUP: Remove old foliage from the last time you pressed Generate
	for child in get_children():
		if child.name.ends_with("_Container") or child.name.ends_with("_MultiMesh"):
			child.free()
			
	for foliage in foliage_types:
		if not foliage: continue
		
		# 2. LOOT CHECK: Does the foliage name contain "-loot"?
		var is_loot = false
		if "-loot" in foliage.name.to_lower():
			is_loot = true
			
		# If it's NOT loot, and it has a mesh, we use optimized multimesh!
		var is_multimesh = not is_loot and foliage.placeholder_mesh != null
		
		# 3. Setup the Container
		var container
		if is_multimesh:
			container = MultiMeshInstance3D.new()
			container.name = foliage.name + "_MultiMesh"
			var mm = MultiMesh.new()
			mm.transform_format = MultiMesh.TRANSFORM_3D
			mm.mesh = foliage.placeholder_mesh
			container.multimesh = mm
			add_child(container)
		else:
			container = Node3D.new()
			container.name = foliage.name + "_Container"
			add_child(container)
			
		# CRITICAL FIX 1: Set the container's owner so Godot saves it!
		if Engine.is_editor_hint() and get_tree() and get_tree().edited_scene_root:
			container.owner = get_tree().edited_scene_root
			
		var spawned_positions = []
		var transform_list = []
		
		# Loop through terrain vertices
		for v in vertices:
			# Only check vertices above water
			if v.y < 0.0: continue 
			
			var is_sand = v.y <= sand_level
			
			# Check sand rules
			if is_sand and not foliage.can_spawn_at_sand: continue
			if not is_sand and foliage.spawn_at_sand_only: continue
			
			# Density check
			if rng.randf() > foliage.density: continue
			
			# Min Distance check
			var too_close = false
			for sp in spawned_positions:
				if sp.distance_to(v) < foliage.min_distance:
					too_close = true
					break
			if too_close: continue
			
			# We passed all rules! Spawn it.
			spawned_positions.append(v)
			
			# Randomize size and rotation
			var scale_val = rng.randf_range(foliage.min_scale, foliage.max_scale)
			var rot_y = rng.randf_range(0, TAU)
			
			var t = Transform3D()
			t = t.scaled(Vector3(scale_val, scale_val, scale_val))
			t = t.rotated(Vector3.UP, rot_y)
			t.origin = v
			
			if is_multimesh:
				transform_list.append(t)
			elif foliage.scene_prefab:
				var instance = foliage.scene_prefab.instantiate()
				instance.transform = t
				container.add_child(instance)
				
				# CRITICAL FIX 2: Set the instance owner so the specific loot object saves!
				if Engine.is_editor_hint() and get_tree() and get_tree().edited_scene_root:
					instance.owner = get_tree().edited_scene_root
					
		# Finalize MultiMesh if we used it
		if is_multimesh:
			container.multimesh.instance_count = transform_list.size()
			for i in transform_list.size():
				container.multimesh.set_instance_transform(i, transform_list[i])


func respawn_foliage() -> void:
	# Ensure the mesh actually exists before trying to extract data from it
	if terrain_mesh_node and terrain_mesh_node.mesh:
		# Extract the mesh arrays from the active surface (0)
		var arrays = terrain_mesh_node.mesh.surface_get_arrays(0)
		
		# Grab the exact vertex coordinates that were calculated when the island was first born
		var vertices = arrays[Mesh.ARRAY_VERTEX]
		
		# Re-run your existing scatter logic! 
		# Your cleanup loop will instantly delete any remaining half-mined rocks, 
		# and place fresh ones using the exact same RNG seed.
		_scatter_foliage(vertices)
